[package]
name = "devnotify"
version = "0.1.0"
description = "Your developer notifications in the menu bar"
authors = ["Mahope"]
edition = "2021"

[lib]
name = "devnotify_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "native-tls"] }
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
